name: Deploy Prod

on:
  push:
    branches: [ release/* ]

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  deploy-dev:
    uses: ./.github/workflows/deploy.yml
    with:
      target-env: prod